### ISSUE TITLE
Import assignment cannot be used when targeting ECMAScript modules

### ISSUE THREAD

**Issue by pahud** [play-with-cdk/play-with-cdk#13]
How can I enable this import assignment syntax support? As most of the typescript samples in `aws-samples/aws-cdk-examples` are written in this syntax like this:

https://github.com/aws-samples/aws-cdk-examples/blob/d85826645180871701f296c8937495b3d3a23a9d/typescript/ecs/cluster/index.ts#L1-L4

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/278432/68380839-916ad100-018b-11ea-9e63-6b7a3951f50e.png">

**Comment by pgarbe** [comment]
Thanks for reporting. Should be fixed with #14

**Comment by bruecktech** [comment]
it looks like #14 does not fix this issue

**Comment by bruecktech** [comment]
Fixed with https://github.com/play-with-cdk/play-with-cdk/commit/3d5e7c2435872070990e87bf5151b504b82b8814
