### ISSUE TITLE
Update CDK version to latest

### ISSUE THREAD

**Issue by eduardomourar** [play-with-cdk/play-with-cdk#21]
I was planning to use play-with-cdk when submitting issue in CDK project, but I need CDK version >= 1.30.0.

**Comment by pgarbe** [comment]
it's live

**Comment by eduardomourar** [comment]
@pgarbe , thanks! I believe there is some weird caching problems happening. When trying to synth this using play-with-cdk:

```typescript
import * as cdk from '@aws-cdk/core';
import * as eks from '@aws-cdk/aws-eks';
import * as ec2 from '@aws-cdk/aws-ec2';

export class AppStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        
        const vpc = new ec2.Vpc(this, 'Vpc');
    
        const cluster = new eks.Cluster(this, 'EksFargate', {
          clusterName: 'eks-cluster',
          vpc,
          coreDnsComputeType: eks.CoreDnsComputeType.FARGATE,
        });
    }
}
```

IntelliSense works fine for `eks.CoreDnsComputeType`, but I get the following error when compiling:

> Error during compile and synth
TSError: ⨯ Unable to compile TypeScript:
../../tmp/app-stack.ts(14,11): error TS2345: Argument of type '{ clusterName: string; vpc: Vpc; coreDnsComputeType: any; }' is not assignable to parameter of type 'ClusterProps'.
Object literal may only specify known properties, and 'coreDnsComputeType' does not exist in type 'ClusterProps'.
../../tmp/app-stack.ts(14,35): error TS2339: Property 'CoreDnsComputeType' does not exist on type 'typeof import("/tmp/node_modules/@aws-cdk/aws-eks/lib/index")'.

**Comment by pgarbe** [comment]
Yes, it's wired. I run into the same issues. I'm looking into it

**Comment by pgarbe** [comment]
It's deployed now.
